### ISSUE TITLE
Not seeing VM information on "health.php" page.

### ISSUE THREAD

**Issue by Qazmat** [Krook9d/PurpleLab#2]
I am not seeing VM information on the health php page. 
![health_page](https://github.com/Krook9d/PurpleLab/assets/109563901/4fbdba57-33f5-4591-b9eb-723418d0334a)
Though I am able to get the IP for the sandbox vm on command line by running the command provided in the docs. Import of the sandbox was successful during the installation as show in the attached screen grab.  Any help would be appreciated. 
![VM Setup during installation](https://github.com/Krook9d/PurpleLab/assets/109563901/dd0ad1a4-f1de-4152-8e9c-4d6c77202290)

**Comment by Krook9d** [comment]
The flask server is running ? 

On the ubuntu server, try 
`VBoxManage showvminfo "sandbox" | grep "State:"`

and

` VBoxManage guestproperty get "sandbox" "/VirtualBox/GuestInfo/Net/0/V4/IP"`
