### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by Hackzen** [Krook9d/PurpleLab#5]
My installation failed, I checked the logs and it turns out that the installation script automatically selects the network interface ens33 for VM creation, while my interface was not that one. We need to add a function to allow selecting this during installation.

![issue](https://github.com/Krook9d/PurpleLab/assets/34860526/3d846ef9-fe04-4747-961a-6f4ee8290365)

**Comment by Krook9d** [comment]
Thank you for your contribution, indeed it's a good point. I have modified the installation script to display the interfaces with their IPs, and then to ask the user 'Which interface does he want to choose for the VM?'

Please relaunch the installation and let me know if it's okay

![image](https://github.com/Krook9d/PurpleLab/assets/40600995/f7895ea3-d024-48dd-b72d-1881c052124c)
